sqlcmd -S .\SQL2022 -d Geonames -i GeonamesQuery.sql -v CountryCode="cn" -v AdminLevel="1" -o "output-cn-1.csv" -s"," -W -u
sqlcmd -S .\SQL2022 -d Geonames -i GeonamesQuery.sql -v CountryCode="cn" -v AdminLevel="2" -o "output-cn-2.csv" -s"," -W -u
sqlcmd -S .\SQL2022 -d Geonames -i GeonamesQuery.sql -v CountryCode="cn" -v AdminLevel="3" -o "output-cn-3.csv" -s"," -W -u
sqlcmd -S .\SQL2022 -d Geonames -i GeonamesQuery.sql -v CountryCode="in" -v AdminLevel="1" -o "output-in-1.csv" -s"," -W -u
sqlcmd -S .\SQL2022 -d Geonames -i GeonamesQuery.sql -v CountryCode="in" -v AdminLevel="2" -o "output-in-2.csv" -s"," -W -u
sqlcmd -S .\SQL2022 -d Geonames -i GeonamesQuery.sql -v CountryCode="in" -v AdminLevel="3" -o "output-in-3.csv" -s"," -W -u
sqlcmd -S .\SQL2022 -d Geonames -i GeonamesQuery.sql -v CountryCode="jp" -v AdminLevel="1" -o "output-jp-1.csv" -s"," -W -u
sqlcmd -S .\SQL2022 -d Geonames -i GeonamesQuery.sql -v CountryCode="jp" -v AdminLevel="2" -o "output-jp-2.csv" -s"," -W -u
sqlcmd -S .\SQL2022 -d Geonames -i GeonamesQuery.sql -v CountryCode="jp" -v AdminLevel="3" -o "output-jp-3.csv" -s"," -W -u
sqlcmd -S .\SQL2022 -d Geonames -i GeonamesQuery.sql -v CountryCode="mn" -v AdminLevel="1" -o "output-mn-1.csv" -s"," -W -u
sqlcmd -S .\SQL2022 -d Geonames -i GeonamesQuery.sql -v CountryCode="mn" -v AdminLevel="2" -o "output-mn-2.csv" -s"," -W -u
sqlcmd -S .\SQL2022 -d Geonames -i GeonamesQuery.sql -v CountryCode="mn" -v AdminLevel="3" -o "output-mn-3.csv" -s"," -W -u
sqlcmd -S .\SQL2022 -d Geonames -i GeonamesQuery.sql -v CountryCode="ph" -v AdminLevel="1" -o "output-ph-1.csv" -s"," -W -u
sqlcmd -S .\SQL2022 -d Geonames -i GeonamesQuery.sql -v CountryCode="ph" -v AdminLevel="2" -o "output-ph-2.csv" -s"," -W -u
sqlcmd -S .\SQL2022 -d Geonames -i GeonamesQuery.sql -v CountryCode="ph" -v AdminLevel="3" -o "output-ph-3.csv" -s"," -W -u
sqlcmd -S .\SQL2022 -d Geonames -i GeonamesQuery.sql -v CountryCode="tr" -v AdminLevel="1" -o "output-tr-1.csv" -s"," -W -u
sqlcmd -S .\SQL2022 -d Geonames -i GeonamesQuery.sql -v CountryCode="tr" -v AdminLevel="2" -o "output-tr-2.csv" -s"," -W -u
sqlcmd -S .\SQL2022 -d Geonames -i GeonamesQuery.sql -v CountryCode="tr" -v AdminLevel="3" -o "output-tr-3.csv" -s"," -W -u
sqlcmd -S .\SQL2022 -d Geonames -i GeonamesQuery.sql -v CountryCode="tw" -v AdminLevel="1" -o "output-tw-1.csv" -s"," -W -u
sqlcmd -S .\SQL2022 -d Geonames -i GeonamesQuery.sql -v CountryCode="tw" -v AdminLevel="2" -o "output-tw-2.csv" -s"," -W -u
sqlcmd -S .\SQL2022 -d Geonames -i GeonamesQuery.sql -v CountryCode="tw" -v AdminLevel="3" -o "output-tw-3.csv" -s"," -W -u
sqlcmd -S .\SQL2022 -d Geonames -i GeonamesQuery.sql -v CountryCode="us" -v AdminLevel="1" -o "output-us-1.csv" -s"," -W -u
sqlcmd -S .\SQL2022 -d Geonames -i GeonamesQuery.sql -v CountryCode="us" -v AdminLevel="2" -o "output-us-2.csv" -s"," -W -u
sqlcmd -S .\SQL2022 -d Geonames -i GeonamesQuery.sql -v CountryCode="us" -v AdminLevel="3" -o "output-us-3.csv" -s"," -W -u